# This file was generated by GoReleaser. DO NOT EDIT.
cask "durablex" do
  version "0.1.0-beta.1"

  on_macos do
    on_intel do
      sha256 "4afcf51622d19573ca8a0684fd1b3957491da3727e89fb64df4383ee1e9fdd0b"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "514a974e45c5239d46c516cf4673d9882da2e277d32ade483e42b5dcbb887006"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "efc26da8b6c7d19c595fb8a4fa9d38ed26e670b3739cbb77ec22ba48a1cdf29c"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b976c1eb5efab1e26d88b5b6d18e214577529743796c52d897d4c8df84aef0e3"
      url "https://github.com/easydep/durablex/releases/download/v#{version}/durablex_#{version}_linux_arm64.tar.gz"
    end
  end

  name "durablex"
  desc "Durable workflow engine - a single Go binary with an embedded dashboard"
  homepage "https://github.com/easydep/durablex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "durablex"

  # No zap stanza required

end
